networks:
  web-proxy:
    external: true

services:
  web:
    build: .
    container_name: joomla_web
    volumes:
      - ./html:/var/www/html
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - web-proxy
      - default
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: joomla_db
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: joomla_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: joomla_db
    networks:
      - default
    depends_on:
      - db
